// <auto-generated />
using System;
using KinderKompas.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KinderKompas.Infrastructure.Migrations
{
    [DbContext(typeof(KinderKompasDbContext))]
    [Migration("20260617210447_Initieel")]
    partial class Initieel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Kind", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Contracttype")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Einddatum")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Geboortedatum")
                        .HasColumnType("date");

                    b.Property<int>("GewensteOpvangdagen")
                        .HasColumnType("int");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StamgroepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Startdatum")
                        .HasColumnType("date");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrganisatieId");

                    b.HasIndex("StamgroepId");

                    b.ToTable("Kinderen");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Medewerker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Contracturen")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<int>("VasteWerkdagen")
                        .HasColumnType("int");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrganisatieId");

                    b.ToTable("Medewerkers");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Organisatie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lrknummer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Organisaties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a000000-0000-0000-0000-000000000001"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Lrknummer = "000000000",
                            Naam = "Op d'n Buiten"
                        });
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Stamgroep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxKinderen")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganisatieId");

                    b.ToTable("Stamgroepen");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b000000-0000-0000-0000-000000000001"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxKinderen = 12,
                            Naam = "Bengeltjes",
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0b000000-0000-0000-0000-000000000002"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxKinderen = 12,
                            Naam = "Boefjes",
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Kind", b =>
                {
                    b.HasOne("KinderKompas.Domain.Entiteiten.Organisatie", "Organisatie")
                        .WithMany("Kinderen")
                        .HasForeignKey("OrganisatieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KinderKompas.Domain.Entiteiten.Stamgroep", "Stamgroep")
                        .WithMany("Kinderen")
                        .HasForeignKey("StamgroepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organisatie");

                    b.Navigation("Stamgroep");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Medewerker", b =>
                {
                    b.HasOne("KinderKompas.Domain.Entiteiten.Organisatie", "Organisatie")
                        .WithMany("Medewerkers")
                        .HasForeignKey("OrganisatieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organisatie");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Stamgroep", b =>
                {
                    b.HasOne("KinderKompas.Domain.Entiteiten.Organisatie", "Organisatie")
                        .WithMany("Stamgroepen")
                        .HasForeignKey("OrganisatieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organisatie");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Organisatie", b =>
                {
                    b.Navigation("Kinderen");

                    b.Navigation("Medewerkers");

                    b.Navigation("Stamgroepen");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Stamgroep", b =>
                {
                    b.Navigation("Kinderen");
                });
#pragma warning restore 612, 618
        }
    }
}
