// <auto-generated />
using System;
using KinderKompas.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KinderKompas.Infrastructure.Migrations
{
    [DbContext(typeof(KinderKompasDbContext))]
    [Migration("20260617213352_IdentityEnAutorisatie")]
    partial class IdentityEnAutorisatie
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Capability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Sleutel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Sleutel")
                        .IsUnique();

                    b.ToTable("Capabilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("533ca9a8-caf9-b9ff-3410-4d086e50b08d"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Omschrijving = "Oudergegevens (contact, telefoon, mail) inzien",
                            Sleutel = "MagOudergegevensZien"
                        },
                        new
                        {
                            Id = new Guid("73b5d451-8c90-336e-a5c4-18449b7533d3"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Omschrijving = "Kindgegevens en plaatsing beheren",
                            Sleutel = "MagKinderenBeheren"
                        },
                        new
                        {
                            Id = new Guid("e904ca58-9b3a-74e1-b988-6d927c70b5b2"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Omschrijving = "Wachtlijst en plaatsingsvoorstellen beheren",
                            Sleutel = "MagWachtlijstBeheren"
                        },
                        new
                        {
                            Id = new Guid("59cb0af1-81b4-eebd-aec1-06149fbd3c1a"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Omschrijving = "Werkrooster opstellen en wijzigen",
                            Sleutel = "MagRoosterBeheren"
                        },
                        new
                        {
                            Id = new Guid("88520ca6-7c25-d792-7ea1-7f5c98503f0a"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Omschrijving = "Werkrooster definitief versturen",
                            Sleutel = "MagRoosterVersturen"
                        },
                        new
                        {
                            Id = new Guid("fe90a764-2947-895f-6ba8-2184df6e59c5"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Omschrijving = "Observaties opstellen en versturen",
                            Sleutel = "MagObservatiesVersturen"
                        },
                        new
                        {
                            Id = new Guid("e85f93b6-c03c-c213-0e21-1c349581f502"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Omschrijving = "Medewerkers en hun rollen beheren",
                            Sleutel = "MagMedewerkersBeheren"
                        },
                        new
                        {
                            Id = new Guid("f45086d0-7b9a-5867-6dfa-55825b170364"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Omschrijving = "Organisatie-instellingen en rechten beheren",
                            Sleutel = "MagInstellingenBeheren"
                        });
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Kind", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Contracttype")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Einddatum")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Geboortedatum")
                        .HasColumnType("date");

                    b.Property<int>("GewensteOpvangdagen")
                        .HasColumnType("int");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StamgroepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Startdatum")
                        .HasColumnType("date");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrganisatieId");

                    b.HasIndex("StamgroepId");

                    b.ToTable("Kinderen");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Medewerker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Contracturen")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentityUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<int>("VasteWerkdagen")
                        .HasColumnType("int");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrganisatieId");

                    b.ToTable("Medewerkers");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Organisatie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lrknummer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Organisaties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a000000-0000-0000-0000-000000000001"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Lrknummer = "000000000",
                            Naam = "Op d'n Buiten"
                        });
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.RolCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CapabilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CapabilityId");

                    b.HasIndex("OrganisatieId", "Rol", "CapabilityId")
                        .IsUnique();

                    b.ToTable("RolCapabilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22f8dc75-db51-0230-d19f-5184a6a1dfaa"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("533ca9a8-caf9-b9ff-3410-4d086e50b08d"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("9e03dfcb-b126-7d7b-3696-71d43494516d"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("73b5d451-8c90-336e-a5c4-18449b7533d3"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("73078a48-aba9-4a1d-8698-648d0c815877"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("e904ca58-9b3a-74e1-b988-6d927c70b5b2"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("02f2fcc8-427c-97cd-4bef-06daa8cc12ac"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("59cb0af1-81b4-eebd-aec1-06149fbd3c1a"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("217c664d-eee1-1a26-1251-8b54660d2236"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("88520ca6-7c25-d792-7ea1-7f5c98503f0a"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("6fd6fc2a-11c0-54c5-3cd1-23e8b5a0544c"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("fe90a764-2947-895f-6ba8-2184df6e59c5"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("0649583d-7fc9-ae53-0505-c40006580cf8"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("e85f93b6-c03c-c213-0e21-1c349581f502"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("475575ef-c7cc-a022-28db-3a0ede0ef554"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("f45086d0-7b9a-5867-6dfa-55825b170364"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("20229c8a-a9c1-91c6-d80a-96c108b43ed5"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("73b5d451-8c90-336e-a5c4-18449b7533d3"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("85cc444f-b664-1442-09c0-9cba249f8327"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("e904ca58-9b3a-74e1-b988-6d927c70b5b2"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("24b677db-c986-9e9e-5952-8bd6982fe112"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("59cb0af1-81b4-eebd-aec1-06149fbd3c1a"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("5a808c6b-f30f-cc48-b56e-687e90a218d3"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("88520ca6-7c25-d792-7ea1-7f5c98503f0a"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("1b5d041c-b612-dae1-3aec-e4dca2f9b037"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("fe90a764-2947-895f-6ba8-2184df6e59c5"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("2ed6d771-6072-52ca-ea4a-6ea9db12baf7"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("e85f93b6-c03c-c213-0e21-1c349581f502"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("c16760ac-c001-6449-aa62-437ea5c2ae74"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("73b5d451-8c90-336e-a5c4-18449b7533d3"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 2
                        },
                        new
                        {
                            Id = new Guid("5cd31be3-00a0-68fa-2e95-25ae6c52c852"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("e904ca58-9b3a-74e1-b988-6d927c70b5b2"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 2
                        },
                        new
                        {
                            Id = new Guid("c3ec8c6c-c4be-f859-4a01-f50f7e2eba57"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("88520ca6-7c25-d792-7ea1-7f5c98503f0a"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 2
                        },
                        new
                        {
                            Id = new Guid("ee1fe437-9a79-ddb4-30a3-ccd4526b9866"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("fe90a764-2947-895f-6ba8-2184df6e59c5"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 2
                        },
                        new
                        {
                            Id = new Guid("4a1965fd-86dd-15a8-22f4-8fb8371d46b2"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("fe90a764-2947-895f-6ba8-2184df6e59c5"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 3
                        },
                        new
                        {
                            Id = new Guid("6a788f24-3700-1dac-8655-7c586ab46755"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("533ca9a8-caf9-b9ff-3410-4d086e50b08d"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 4
                        },
                        new
                        {
                            Id = new Guid("c2dcaad8-24e7-5675-a3de-6e32ebf9c98b"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("73b5d451-8c90-336e-a5c4-18449b7533d3"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 4
                        },
                        new
                        {
                            Id = new Guid("0b94099f-7e05-39fe-f3b3-ff660a5c7652"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("fe90a764-2947-895f-6ba8-2184df6e59c5"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 4
                        });
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Stamgroep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxKinderen")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganisatieId");

                    b.ToTable("Stamgroepen");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b000000-0000-0000-0000-000000000001"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxKinderen = 12,
                            Naam = "Bengeltjes",
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0b000000-0000-0000-0000-000000000002"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxKinderen = 12,
                            Naam = "Boefjes",
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("KinderKompas.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("MedewerkerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("OrganisatieId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KinderKompas.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("IngetrokkenOp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("VerlooptOp")
                        .HasColumnType("datetime2");

                    b.Property<string>("VervangenDoorTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Kind", b =>
                {
                    b.HasOne("KinderKompas.Domain.Entiteiten.Organisatie", "Organisatie")
                        .WithMany("Kinderen")
                        .HasForeignKey("OrganisatieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KinderKompas.Domain.Entiteiten.Stamgroep", "Stamgroep")
                        .WithMany("Kinderen")
                        .HasForeignKey("StamgroepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("KinderKompas.Domain.ValueObjects.Oudercontact", "Oudercontact", b1 =>
                        {
                            b1.Property<Guid>("KindId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Oudercontact_Email");

                            b1.Property<string>("Naam")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Oudercontact_Naam");

                            b1.Property<string>("Telefoon")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("Oudercontact_Telefoon");

                            b1.HasKey("KindId");

                            b1.ToTable("Kinderen");

                            b1.WithOwner()
                                .HasForeignKey("KindId");
                        });

                    b.Navigation("Organisatie");

                    b.Navigation("Oudercontact");

                    b.Navigation("Stamgroep");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Medewerker", b =>
                {
                    b.HasOne("KinderKompas.Domain.Entiteiten.Organisatie", "Organisatie")
                        .WithMany("Medewerkers")
                        .HasForeignKey("OrganisatieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organisatie");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.RolCapability", b =>
                {
                    b.HasOne("KinderKompas.Domain.Entiteiten.Capability", "Capability")
                        .WithMany("RolCapabilities")
                        .HasForeignKey("CapabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capability");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Stamgroep", b =>
                {
                    b.HasOne("KinderKompas.Domain.Entiteiten.Organisatie", "Organisatie")
                        .WithMany("Stamgroepen")
                        .HasForeignKey("OrganisatieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organisatie");
                });

            modelBuilder.Entity("KinderKompas.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.HasOne("KinderKompas.Infrastructure.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KinderKompas.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KinderKompas.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KinderKompas.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KinderKompas.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Capability", b =>
                {
                    b.Navigation("RolCapabilities");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Organisatie", b =>
                {
                    b.Navigation("Kinderen");

                    b.Navigation("Medewerkers");

                    b.Navigation("Stamgroepen");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Stamgroep", b =>
                {
                    b.Navigation("Kinderen");
                });
#pragma warning restore 612, 618
        }
    }
}
