// <auto-generated />
using System;
using KinderKompas.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KinderKompas.Infrastructure.Migrations
{
    [DbContext(typeof(KinderKompasDbContext))]
    [Migration("20260622165102_VoegPlanningZienCapabilityToe")]
    partial class VoegPlanningZienCapabilityToe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Capability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Sleutel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Sleutel")
                        .IsUnique();

                    b.ToTable("Capabilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("533ca9a8-caf9-b9ff-3410-4d086e50b08d"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Omschrijving = "Oudergegevens (contact, telefoon, mail) inzien",
                            Sleutel = "MagOudergegevensZien"
                        },
                        new
                        {
                            Id = new Guid("73b5d451-8c90-336e-a5c4-18449b7533d3"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Omschrijving = "Kindgegevens en plaatsing beheren",
                            Sleutel = "MagKinderenBeheren"
                        },
                        new
                        {
                            Id = new Guid("b93b92f3-6b02-630e-dda7-8c24442412b1"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Omschrijving = "Weekplanning en dagfilter inzien (alleen-lezen)",
                            Sleutel = "MagPlanningZien"
                        },
                        new
                        {
                            Id = new Guid("e904ca58-9b3a-74e1-b988-6d927c70b5b2"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Omschrijving = "Wachtlijst en plaatsingsvoorstellen beheren",
                            Sleutel = "MagWachtlijstBeheren"
                        },
                        new
                        {
                            Id = new Guid("59cb0af1-81b4-eebd-aec1-06149fbd3c1a"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Omschrijving = "Werkrooster opstellen en wijzigen",
                            Sleutel = "MagRoosterBeheren"
                        },
                        new
                        {
                            Id = new Guid("88520ca6-7c25-d792-7ea1-7f5c98503f0a"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Omschrijving = "Werkrooster definitief versturen",
                            Sleutel = "MagRoosterVersturen"
                        },
                        new
                        {
                            Id = new Guid("fe90a764-2947-895f-6ba8-2184df6e59c5"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Omschrijving = "Observaties opstellen en versturen",
                            Sleutel = "MagObservatiesVersturen"
                        },
                        new
                        {
                            Id = new Guid("e85f93b6-c03c-c213-0e21-1c349581f502"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Omschrijving = "Medewerkers en hun rollen beheren",
                            Sleutel = "MagMedewerkersBeheren"
                        },
                        new
                        {
                            Id = new Guid("f45086d0-7b9a-5867-6dfa-55825b170364"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Omschrijving = "Organisatie-instellingen en rechten beheren",
                            Sleutel = "MagInstellingenBeheren"
                        },
                        new
                        {
                            Id = new Guid("d7b7e8f0-c6e1-61b3-0a88-0ecf6242600b"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Omschrijving = "Dashboard en het actiecentrum (meldingen/to-do's) inzien",
                            Sleutel = "MagDashboardZien"
                        },
                        new
                        {
                            Id = new Guid("d964b02e-1fb6-4050-a044-13488445cf14"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Omschrijving = "Groepsportaal op locatie gebruiken (inklokken, dienst, observaties)",
                            Sleutel = "MagGroepsportaalGebruiken"
                        },
                        new
                        {
                            Id = new Guid("c8b888f7-520c-8350-c7d2-f5723eb7517a"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Omschrijving = "Thuis-portaal gebruiken (eigen rooster, beschikbaarheid, verlof)",
                            Sleutel = "MagThuisportaalGebruiken"
                        });
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Kind", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Contracttype")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("Einddatum")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Geboortedatum")
                        .HasColumnType("date");

                    b.Property<int>("GewensteOpvangdagen")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("MentorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StamgroepId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Startdatum")
                        .HasColumnType("date");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.HasIndex("OrganisatieId");

                    b.HasIndex("StamgroepId");

                    b.ToTable("Kinderen");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Medewerker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Beschikbaarheidsdagen")
                        .HasColumnType("integer");

                    b.Property<decimal>("Contracturen")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IdentityUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<Guid?>("VasteStamgroepId")
                        .HasColumnType("uuid");

                    b.Property<int>("VasteWerkdagen")
                        .HasColumnType("integer");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrganisatieId");

                    b.HasIndex("VasteStamgroepId");

                    b.ToTable("Medewerkers");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Melding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("AfgehandeldOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("BronId")
                        .HasColumnType("uuid");

                    b.Property<string>("BronType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeduplicatieSleutel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uuid");

                    b.Property<int>("Soort")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("VereistActie")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("OrganisatieId", "Status");

                    b.HasIndex("OrganisatieId", "DeduplicatieSleutel", "Status");

                    b.ToTable("Meldingen");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Observatie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("BestandsGrootte")
                        .HasColumnType("bigint");

                    b.Property<string>("BestandsNaam")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("BestandsSleutel")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("KindId")
                        .HasColumnType("uuid");

                    b.Property<int>("MijlpaalMaanden")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerzondenNaarEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("VerzondenOp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("KindId", "MijlpaalMaanden")
                        .IsUnique();

                    b.ToTable("Observaties");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Organisatie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Lrknummer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Organisaties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a000000-0000-0000-0000-000000000001"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Lrknummer = "000000000",
                            Naam = "Op d'n Buiten"
                        });
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.OrganisatieInstellingen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("KindBinnenkortVierDrempelDagen")
                        .HasColumnType("integer");

                    b.Property<int>("ObservatieBinnenkortDrempelDagen")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uuid");

                    b.Property<int>("PrioriteitInternGewicht")
                        .HasColumnType("integer");

                    b.Property<int>("PrioriteitPerMaandGewicht")
                        .HasColumnType("integer");

                    b.Property<string>("StandaardObservatietekst")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("VerborgenMeldingsoorten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrganisatieId")
                        .IsUnique();

                    b.ToTable("OrganisatieInstellingen");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c000000-0000-0000-0000-000000000001"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            KindBinnenkortVierDrempelDagen = 90,
                            ObservatieBinnenkortDrempelDagen = 30,
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            PrioriteitInternGewicht = 500,
                            PrioriteitPerMaandGewicht = 10,
                            VerborgenMeldingsoorten = ""
                        });
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.RolCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CapabilityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CapabilityId");

                    b.HasIndex("OrganisatieId", "Rol", "CapabilityId")
                        .IsUnique();

                    b.ToTable("RolCapabilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22f8dc75-db51-0230-d19f-5184a6a1dfaa"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("533ca9a8-caf9-b9ff-3410-4d086e50b08d"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("9e03dfcb-b126-7d7b-3696-71d43494516d"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("73b5d451-8c90-336e-a5c4-18449b7533d3"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("20a2771f-6db5-b709-015e-777298a61aa6"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("b93b92f3-6b02-630e-dda7-8c24442412b1"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("73078a48-aba9-4a1d-8698-648d0c815877"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("e904ca58-9b3a-74e1-b988-6d927c70b5b2"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("02f2fcc8-427c-97cd-4bef-06daa8cc12ac"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("59cb0af1-81b4-eebd-aec1-06149fbd3c1a"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("217c664d-eee1-1a26-1251-8b54660d2236"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("88520ca6-7c25-d792-7ea1-7f5c98503f0a"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("6fd6fc2a-11c0-54c5-3cd1-23e8b5a0544c"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("fe90a764-2947-895f-6ba8-2184df6e59c5"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("0649583d-7fc9-ae53-0505-c40006580cf8"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("e85f93b6-c03c-c213-0e21-1c349581f502"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("475575ef-c7cc-a022-28db-3a0ede0ef554"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("f45086d0-7b9a-5867-6dfa-55825b170364"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("8e76cde6-0e4d-0ba1-f541-d9a82152ea89"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("d7b7e8f0-c6e1-61b3-0a88-0ecf6242600b"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("6a45542c-1ee8-400e-823e-cbbb3db4a8c0"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("c8b888f7-520c-8350-c7d2-f5723eb7517a"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("20229c8a-a9c1-91c6-d80a-96c108b43ed5"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("73b5d451-8c90-336e-a5c4-18449b7533d3"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("562b968a-d2f6-9128-ebd2-7ad756061ba9"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("b93b92f3-6b02-630e-dda7-8c24442412b1"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("85cc444f-b664-1442-09c0-9cba249f8327"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("e904ca58-9b3a-74e1-b988-6d927c70b5b2"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("24b677db-c986-9e9e-5952-8bd6982fe112"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("59cb0af1-81b4-eebd-aec1-06149fbd3c1a"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("5a808c6b-f30f-cc48-b56e-687e90a218d3"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("88520ca6-7c25-d792-7ea1-7f5c98503f0a"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("1b5d041c-b612-dae1-3aec-e4dca2f9b037"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("fe90a764-2947-895f-6ba8-2184df6e59c5"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("2ed6d771-6072-52ca-ea4a-6ea9db12baf7"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("e85f93b6-c03c-c213-0e21-1c349581f502"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("f9953744-0012-bc39-80e1-d0df5dd77c2f"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("d7b7e8f0-c6e1-61b3-0a88-0ecf6242600b"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("b8faed65-f228-2629-8cd8-61b654fde6cf"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("c8b888f7-520c-8350-c7d2-f5723eb7517a"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("a599e2b6-341a-1976-ec59-385bd3d86304"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("b93b92f3-6b02-630e-dda7-8c24442412b1"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 2
                        },
                        new
                        {
                            Id = new Guid("c3ec8c6c-c4be-f859-4a01-f50f7e2eba57"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("88520ca6-7c25-d792-7ea1-7f5c98503f0a"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 2
                        },
                        new
                        {
                            Id = new Guid("ee1fe437-9a79-ddb4-30a3-ccd4526b9866"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("fe90a764-2947-895f-6ba8-2184df6e59c5"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 2
                        },
                        new
                        {
                            Id = new Guid("4e41907a-bedf-f19f-78b6-cb3ef1247215"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("c8b888f7-520c-8350-c7d2-f5723eb7517a"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 2
                        },
                        new
                        {
                            Id = new Guid("4a1965fd-86dd-15a8-22f4-8fb8371d46b2"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("fe90a764-2947-895f-6ba8-2184df6e59c5"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 3
                        },
                        new
                        {
                            Id = new Guid("208206c0-1691-8ede-fc6b-82df6f71fd83"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("c8b888f7-520c-8350-c7d2-f5723eb7517a"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 3
                        },
                        new
                        {
                            Id = new Guid("6a788f24-3700-1dac-8655-7c586ab46755"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("533ca9a8-caf9-b9ff-3410-4d086e50b08d"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 4
                        },
                        new
                        {
                            Id = new Guid("c2dcaad8-24e7-5675-a3de-6e32ebf9c98b"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("73b5d451-8c90-336e-a5c4-18449b7533d3"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 4
                        },
                        new
                        {
                            Id = new Guid("93ebd198-fdd3-59b3-16db-a6232f25e583"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("b93b92f3-6b02-630e-dda7-8c24442412b1"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 4
                        },
                        new
                        {
                            Id = new Guid("0b94099f-7e05-39fe-f3b3-ff660a5c7652"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("fe90a764-2947-895f-6ba8-2184df6e59c5"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 4
                        },
                        new
                        {
                            Id = new Guid("1a51ec29-a7a0-a0c9-fd46-8916cda2b2e4"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CapabilityId = new Guid("d964b02e-1fb6-4050-a044-13488445cf14"),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001"),
                            Rol = 4
                        });
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Roosterdienst", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("MedewerkerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoosterweekId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StamgroepId")
                        .HasColumnType("uuid");

                    b.Property<string>("Taakomschrijving")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UrencorrectieKwartieren")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoosterweekId");

                    b.HasIndex("StamgroepId");

                    b.HasIndex("MedewerkerId", "Datum", "StamgroepId")
                        .IsUnique();

                    b.ToTable("Roosterdiensten");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Roosterweek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VerstuurdOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly>("WeekBegin")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("OrganisatieId", "WeekBegin")
                        .IsUnique();

                    b.ToTable("Roosterweken");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Schoolvakantie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly>("Begindatum")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Einddatum")
                        .HasColumnType("date");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uuid");

                    b.Property<int>("Schooljaar")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganisatieId", "Schooljaar");

                    b.ToTable("Schoolvakanties");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Stamgroep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MaxKinderen")
                        .HasColumnType("integer");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganisatieId");

                    b.ToTable("Stamgroepen");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b000000-0000-0000-0000-000000000001"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxKinderen = 12,
                            Naam = "Bengeltjes",
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0b000000-0000-0000-0000-000000000002"),
                            AangemaaktOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GewijzigdOp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxKinderen = 12,
                            Naam = "Boefjes",
                            OrganisatieId = new Guid("0a000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Urenregistratie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Ingeklokt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("MedewerkerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoosterdienstId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StamgroepId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Uitgeklokt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MedewerkerId");

                    b.HasIndex("RoosterdienstId");

                    b.HasIndex("StamgroepId");

                    b.HasIndex("OrganisatieId", "MedewerkerId", "Datum");

                    b.ToTable("Urenregistraties");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Verlofaanvraag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("AantalUren")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateOnly>("Begindatum")
                        .HasColumnType("date");

                    b.Property<DateTime?>("BeoordeeldOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("BeoordelingsNotitie")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Categorie")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Einddatum")
                        .HasColumnType("date");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("MedewerkerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reden")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MedewerkerId");

                    b.HasIndex("OrganisatieId", "Status");

                    b.ToTable("Verlofaanvragen");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Verlofsaldo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Categorie")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("MedewerkerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ToegekendeUren")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateOnly?>("Vervaldatum")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MedewerkerId", "Categorie")
                        .IsUnique();

                    b.ToTable("Verlofsaldi");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Voorstel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("BeantwoordOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notitie")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("VerstuurdOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("VoorgesteldeDagen")
                        .HasColumnType("integer");

                    b.Property<Guid>("VoorgesteldeStamgroepId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WachtlijstInschrijvingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VoorgesteldeStamgroepId");

                    b.HasIndex("WachtlijstInschrijvingId");

                    b.ToTable("Voorstellen");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.VoorstelDag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("VoorgesteldeDatum")
                        .HasColumnType("date");

                    b.Property<Guid>("VoorstelId")
                        .HasColumnType("uuid");

                    b.Property<int>("Weekdag")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VoorstelId", "Weekdag")
                        .IsUnique();

                    b.ToTable("VoorstelDagen");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.WachtlijstInschrijving", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Contracttype")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Geboortedatum")
                        .HasColumnType("date");

                    b.Property<int>("GewensteOpvangdagen")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GewensteStamgroepId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("GewensteStartdatum")
                        .HasColumnType("date");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("HandmatigBovenaan")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("InschrijfdatumWachtlijst")
                        .HasColumnType("date");

                    b.Property<bool>("IsIntern")
                        .HasColumnType("boolean");

                    b.Property<string>("Notitie")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReedsGeplaatsteDagen")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GewensteStamgroepId");

                    b.HasIndex("OrganisatieId", "Status");

                    b.ToTable("Wachtlijstinschrijvingen");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Ziekmelding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly>("Begindatum")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("Einddatum")
                        .HasColumnType("date");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("MedewerkerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MedewerkerId");

                    b.HasIndex("OrganisatieId", "MedewerkerId");

                    b.ToTable("Ziekmeldingen");
                });

            modelBuilder.Entity("KinderKompas.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MedewerkerId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("OrganisatieId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KinderKompas.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("IngetrokkenOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("OrganisatieId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("VerlooptOp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VervangenDoorTokenHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Kind", b =>
                {
                    b.HasOne("KinderKompas.Domain.Entiteiten.Medewerker", "Mentor")
                        .WithMany()
                        .HasForeignKey("MentorId");

                    b.HasOne("KinderKompas.Domain.Entiteiten.Organisatie", "Organisatie")
                        .WithMany("Kinderen")
                        .HasForeignKey("OrganisatieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KinderKompas.Domain.Entiteiten.Stamgroep", "Stamgroep")
                        .WithMany("Kinderen")
                        .HasForeignKey("StamgroepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("KinderKompas.Domain.ValueObjects.Oudercontact", "Oudercontact", b1 =>
                        {
                            b1.Property<Guid>("KindId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Oudercontact_Email");

                            b1.Property<string>("Naam")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Oudercontact_Naam");

                            b1.Property<string>("Telefoon")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("Oudercontact_Telefoon");

                            b1.HasKey("KindId");

                            b1.ToTable("Kinderen");

                            b1.WithOwner()
                                .HasForeignKey("KindId");
                        });

                    b.Navigation("Mentor");

                    b.Navigation("Organisatie");

                    b.Navigation("Oudercontact");

                    b.Navigation("Stamgroep");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Medewerker", b =>
                {
                    b.HasOne("KinderKompas.Domain.Entiteiten.Organisatie", "Organisatie")
                        .WithMany("Medewerkers")
                        .HasForeignKey("OrganisatieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KinderKompas.Domain.Entiteiten.Stamgroep", "VasteStamgroep")
                        .WithMany()
                        .HasForeignKey("VasteStamgroepId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Organisatie");

                    b.Navigation("VasteStamgroep");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Observatie", b =>
                {
                    b.HasOne("KinderKompas.Domain.Entiteiten.Kind", "Kind")
                        .WithMany()
                        .HasForeignKey("KindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kind");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.RolCapability", b =>
                {
                    b.HasOne("KinderKompas.Domain.Entiteiten.Capability", "Capability")
                        .WithMany("RolCapabilities")
                        .HasForeignKey("CapabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capability");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Roosterdienst", b =>
                {
                    b.HasOne("KinderKompas.Domain.Entiteiten.Medewerker", "Medewerker")
                        .WithMany()
                        .HasForeignKey("MedewerkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KinderKompas.Domain.Entiteiten.Roosterweek", "Roosterweek")
                        .WithMany("Diensten")
                        .HasForeignKey("RoosterweekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KinderKompas.Domain.Entiteiten.Stamgroep", "Stamgroep")
                        .WithMany()
                        .HasForeignKey("StamgroepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medewerker");

                    b.Navigation("Roosterweek");

                    b.Navigation("Stamgroep");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Schoolvakantie", b =>
                {
                    b.HasOne("KinderKompas.Domain.Entiteiten.Organisatie", "Organisatie")
                        .WithMany("Schoolvakanties")
                        .HasForeignKey("OrganisatieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organisatie");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Stamgroep", b =>
                {
                    b.HasOne("KinderKompas.Domain.Entiteiten.Organisatie", "Organisatie")
                        .WithMany("Stamgroepen")
                        .HasForeignKey("OrganisatieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organisatie");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Urenregistratie", b =>
                {
                    b.HasOne("KinderKompas.Domain.Entiteiten.Medewerker", "Medewerker")
                        .WithMany()
                        .HasForeignKey("MedewerkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KinderKompas.Domain.Entiteiten.Roosterdienst", "Roosterdienst")
                        .WithMany()
                        .HasForeignKey("RoosterdienstId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KinderKompas.Domain.Entiteiten.Stamgroep", "Stamgroep")
                        .WithMany()
                        .HasForeignKey("StamgroepId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Medewerker");

                    b.Navigation("Roosterdienst");

                    b.Navigation("Stamgroep");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Verlofaanvraag", b =>
                {
                    b.HasOne("KinderKompas.Domain.Entiteiten.Medewerker", "Medewerker")
                        .WithMany()
                        .HasForeignKey("MedewerkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medewerker");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Verlofsaldo", b =>
                {
                    b.HasOne("KinderKompas.Domain.Entiteiten.Medewerker", "Medewerker")
                        .WithMany()
                        .HasForeignKey("MedewerkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medewerker");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Voorstel", b =>
                {
                    b.HasOne("KinderKompas.Domain.Entiteiten.Stamgroep", "VoorgesteldeStamgroep")
                        .WithMany()
                        .HasForeignKey("VoorgesteldeStamgroepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KinderKompas.Domain.Entiteiten.WachtlijstInschrijving", "WachtlijstInschrijving")
                        .WithMany("Voorstellen")
                        .HasForeignKey("WachtlijstInschrijvingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VoorgesteldeStamgroep");

                    b.Navigation("WachtlijstInschrijving");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.VoorstelDag", b =>
                {
                    b.HasOne("KinderKompas.Domain.Entiteiten.Voorstel", "Voorstel")
                        .WithMany("Dagen")
                        .HasForeignKey("VoorstelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voorstel");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.WachtlijstInschrijving", b =>
                {
                    b.HasOne("KinderKompas.Domain.Entiteiten.Stamgroep", "GewensteStamgroep")
                        .WithMany()
                        .HasForeignKey("GewensteStamgroepId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KinderKompas.Domain.Entiteiten.Organisatie", "Organisatie")
                        .WithMany()
                        .HasForeignKey("OrganisatieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("KinderKompas.Domain.ValueObjects.Oudercontact", "Oudercontact", b1 =>
                        {
                            b1.Property<Guid>("WachtlijstInschrijvingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Oudercontact_Email");

                            b1.Property<string>("Naam")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Oudercontact_Naam");

                            b1.Property<string>("Telefoon")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("Oudercontact_Telefoon");

                            b1.HasKey("WachtlijstInschrijvingId");

                            b1.ToTable("Wachtlijstinschrijvingen");

                            b1.WithOwner()
                                .HasForeignKey("WachtlijstInschrijvingId");
                        });

                    b.Navigation("GewensteStamgroep");

                    b.Navigation("Organisatie");

                    b.Navigation("Oudercontact");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Ziekmelding", b =>
                {
                    b.HasOne("KinderKompas.Domain.Entiteiten.Medewerker", "Medewerker")
                        .WithMany()
                        .HasForeignKey("MedewerkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medewerker");
                });

            modelBuilder.Entity("KinderKompas.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.HasOne("KinderKompas.Infrastructure.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KinderKompas.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KinderKompas.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KinderKompas.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KinderKompas.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Capability", b =>
                {
                    b.Navigation("RolCapabilities");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Organisatie", b =>
                {
                    b.Navigation("Kinderen");

                    b.Navigation("Medewerkers");

                    b.Navigation("Schoolvakanties");

                    b.Navigation("Stamgroepen");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Roosterweek", b =>
                {
                    b.Navigation("Diensten");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Stamgroep", b =>
                {
                    b.Navigation("Kinderen");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.Voorstel", b =>
                {
                    b.Navigation("Dagen");
                });

            modelBuilder.Entity("KinderKompas.Domain.Entiteiten.WachtlijstInschrijving", b =>
                {
                    b.Navigation("Voorstellen");
                });
#pragma warning restore 612, 618
        }
    }
}
